/**
 * probe-scores.mjs — decisive diagnostic for recall ranking issues.
 *
 * Prints per-result vectorSimilarity + fusedScore + signals for any query,
 * so the similarity floor can be calibrated from real data instead of guesses.
 * Also verifies the write path end-to-end (store → vectorWritten → recall).
 *
 * Usage (PowerShell, from repo root):
 *   $env:MEMRON_MCP_URL='https://memron-ai.onrender.com/mcp'
 *   $env:MEMRON_API_KEY='mm_live_...'
 *   node scripts/probe-scores.mjs "What is the capital of Atlantis?" hybrid 10
 *   node scripts/probe-scores.mjs --store-check "canary phrase here"
 *   node scripts/probe-scores.mjs --diag
 *   node scripts/probe-scores.mjs --debug ptr_xxxxxxxx
 *   node scripts/probe-scores.mjs --multihop
 */
const endpoint = (process.env.MEMRON_MCP_URL || 'http://localhost:4201/mcp').replace(/\/+$/, '');
const apiKey = process.env.MEMRON_API_KEY;
if (!apiKey) {
  console.error('Missing MEMRON_API_KEY.');
  process.exit(1);
}

let sid = null;
let rid = 0;

async function rpc(method, params = {}) {
  const headers = {
    Authorization: `Bearer ${apiKey}`,
    'Content-Type': 'application/json',
    Accept: 'application/json, text/event-stream',
  };
  if (sid) headers['Mcp-Session-Id'] = sid;
  const res = await fetch(endpoint, {
    method: 'POST', headers,
    body: JSON.stringify({ jsonrpc: '2.0', id: ++rid, method, params }),
  });
  const msid = res.headers.get('mcp-session-id');
  if (msid) sid = msid;
  const text = await res.text();
  const line = text.split('\n').find((l) => l.startsWith('data: '));
  return JSON.parse(line ? line.slice(6) : text);
}

async function tool(name, args) {
  const json = await rpc('tools/call', { name, arguments: args });
  if (json.error) throw new Error(JSON.stringify(json.error));
  return JSON.parse(json.result?.content?.[0]?.text ?? '{}');
}

function printResults(payload, label) {
  console.log(`\n--- ${label} ---`);
  console.log(`totalFound=${payload.totalFound} diagnostics=${JSON.stringify(payload.diagnostics || {})}`);
  for (const r of payload.results || []) {
    const sim = r.vectorSimilarity == null ? 'null' : Number(r.vectorSimilarity).toFixed(3);
    console.log(
      `sim=${sim} fused=${r.fusedScore} ptr=${r.pointerId} ` +
      `title=${JSON.stringify((r.title || '').slice(0, 60))}`
    );
  }
}

const mode = process.argv[2];

await rpc('initialize', {
  protocolVersion: '2025-03-26', capabilities: {},
  clientInfo: { name: 'probe-scores', version: '1.0' },
});

if (mode === '--diag') {
  const d = await tool('system_diagnostics', {});
  console.log(JSON.stringify(d, null, 2));
} else if (mode === '--debug') {
  const pointerId = process.argv[3];
  if (!pointerId) {
    console.error('Usage: node scripts/probe-scores.mjs --debug <pointerId>');
    process.exit(1);
  }
  const d = await tool('memory_debug', { pointerId });
  console.log(JSON.stringify(d, null, 2));
} else if (mode === '--multihop') {
  // End-to-end multi-hop check: store a related pair, verify both got
  // vectors, recall the compound question, judge whether BOTH facts surface.
  const f1 = 'Memron uses PostgreSQL with pgvector for vector similarity search.';
  const f2 = 'The default vector dimensions in Memron are 1024, generated by Gemini Embedding 2.';
  const r1 = await tool('memory_store', { content: f1, type: 'fact', tags: ['probe', 'multihop'], bucket: 'knowledge', source: 'cli' });
  const r2 = await tool('memory_store', { content: f2, type: 'fact', tags: ['probe', 'multihop'], bucket: 'knowledge', source: 'cli' });
  console.log('fact1:', r1.pointerId, JSON.stringify(r1.semanticIndex));
  console.log('fact2:', r2.pointerId, JSON.stringify(r2.semanticIndex));
  await new Promise((r) => setTimeout(r, 8000));
  const d1 = await tool('memory_debug', { pointerId: r1.pointerId });
  const d2 = await tool('memory_debug', { pointerId: r2.pointerId });
  console.log('debug1 verdict:', d1.verdict, '| has_embedding:', d1.row?.has_embedding, '| dims:', d1.row?.dims);
  console.log('debug2 verdict:', d2.verdict, '| has_embedding:', d2.row?.has_embedding, '| dims:', d2.row?.dims);
  const q = await tool('memory_recall', {
    query: 'What database and embedding model does Memron use for vector search?',
    mode: 'hybrid', category: 'all', limit: 10, tokenBudget: 2000, format: 'json',
  });
  printResults(q, 'multihop compound recall');
  const all = JSON.stringify(q.results || []).toLowerCase();
  const hasPg = all.includes('pgvector') || all.includes('postgresql');
  const hasGem = all.includes('gemini') || all.includes('1024');
  console.log(`\nVERDICT: pgvector-fact=${hasPg ? 'FOUND' : 'MISSING'} gemini-fact=${hasGem ? 'FOUND' : 'MISSING'} => ${hasPg && hasGem ? 'MULTIHOP OK' : 'MULTIHOP FAIL'}`);
  console.log(`(cleanup: delete ${r1.pointerId} and ${r2.pointerId} via memory_manage when done)`);
} else if (mode === '--store-check') {
  const canary = process.argv.slice(3).join(' ') || `zephyr-probe-${Date.now()}`;
  const content = `Probe diagnostic fact. The secret canary phrase is ${canary}.`;
  const stored = await tool('memory_store', {
    content, type: 'fact', tags: ['probe'], bucket: 'knowledge', source: 'cli',
  });
  console.log('store semanticIndex:', JSON.stringify(stored.semanticIndex));
  console.log('pointerId:', stored.pointerId);
  await new Promise((r) => setTimeout(r, 8000));
  const v = await tool('memory_recall', {
    query: `secret canary phrase ${canary}`, mode: 'vector',
    category: 'all', limit: 10, tokenBudget: 2000, format: 'json',
  });
  printResults(v, 'vector recall of fresh canary');
} else {
  const query = process.argv[2] || 'What is the capital of Atlantis?';
  const m = process.argv[3] || 'hybrid';
  const limit = Number(process.argv[4] || 10);
  const payload = await tool('memory_recall', {
    query, mode: m, category: 'all', limit, tokenBudget: 2000, format: 'json',
  });
  printResults(payload, `${m} recall: ${query}`);
}
